export const SECURITY_LAB_REPO = 'https://github.com/xuanhai0913/RAT-HAILAMDEV';

export const securityLabCopy = {
  en: {
    back: 'Back to portfolio',
    eyebrow: 'Engineering case study / 2026',
    title: 'Inside the',
    titleAccent: 'trust boundary.',
    intro: 'A Python client/server lab exploring what encryption protects — and what it leaves to the application.',
    project: 'RAT-HAILAMDEV',
    status: 'Learning & defensive research',
    source: 'Explore the repository',
    inspect: 'Explore the architecture',
    brief: 'The project in 30 seconds',
    summary: 'I built a small remote-administration lab to study socket programming, TLS and message handling. The useful lesson: an encrypted connection still needs identity, permissions and clear limits.',
    facts: [
      { label: 'My focus', value: 'Python & network programming' },
      { label: 'Transport', value: 'TLS 1.3 / TCP sockets' },
      { label: 'Protocol', value: 'Newline-delimited JSON' },
      { label: 'Scope', value: 'Isolated learning lab' },
    ],
    architecture: 'Follow the connection.',
    architectureIntro: 'Select a layer to inspect the engineering decision behind it.',
    modelLabel: 'Architecture walkthrough',
    diagramLabel: 'Illustration · no live connection',
    layers: [
      { id: 'client', title: 'Client', tag: '01 / INTERFACE', short: 'CLI · request / response', heading: 'A small, explicit interface.', body: 'The command-line client exchanges action-based requests and responses with the server. The message boundary is a newline, so the receiver can reconstruct JSON messages from a stream of bytes.', noteLabel: 'Full-stack connection', note: 'The same design question appears in APIs: how does a caller know where one message ends and the next begins?', evidence: 'JSON protocol', anchor: '#features' },
      { id: 'transport', title: 'TLS 1.3', tag: '02 / TRANSPORT', short: 'Encrypted channel', heading: 'Privacy on the wire.', body: 'TLS wraps the TCP socket. Certificate verification is part of trusting the peer; a self-signed certificate keeps this project in a learning environment.', noteLabel: 'Key distinction', note: 'Transport encryption protects the connection. It does not decide which application actions a client is allowed to perform.', evidence: 'Transport & lab setup', anchor: '#security-notes' },
      { id: 'server', title: 'Server', tag: '03 / APPLICATION', short: 'Handlers · session state', heading: 'Where application trust starts.', body: 'The Python server dispatches requests, manages clients with locks and writes session records when it stops. These are useful exercises in concurrency and shared state.', noteLabel: 'Current limitation', note: 'The repository documents missing client authentication and authorization. The lab is not presented as a production security product.', evidence: 'Documented limitations', anchor: '#security-notes' },
    ],
    sourceNote: 'Read the source notes',
    lessonsTitle: 'What I would harden next.',
    lessonsIntro: 'A review of the current lab, with the next controls made explicit. These are proposed improvements, not shipped features.',
    current: 'In the current lab',
    next: 'Proposed next step',
    lessons: [
      { title: 'Identity & permissions', current: 'Client authentication and authorization are not implemented.', next: 'Authenticate the client, then authorize each action with the minimum required privileges.' },
      { title: 'Filesystem boundaries', current: 'File paths are not sandboxed.', next: 'Constrain access to an explicit workspace and validate paths at the boundary.' },
      { title: 'Sensitive capabilities', current: 'Optional keystroke and screen-capture modules increase the impact of misuse.', next: 'Remove these capabilities from a minimal defensive demo and keep experiments isolated.' },
    ],
    takeawayLabel: 'What this adds to my full-stack work',
    takeaway: 'Think beyond the happy path.',
    takeawayBody: 'Protocol design, concurrent state and trust boundaries also matter in web backends. This lab gives me a concrete way to discuss those decisions and their limitations.',
    footerNote: 'Based on the public repository. The diagram illustrates the architecture; it does not run the remote-administration tool.',
  },
  vi: {
    back: 'Về portfolio',
    eyebrow: 'Câu chuyện kỹ thuật / 2026',
    title: 'Bên trong',
    titleAccent: 'ranh giới tin cậy.',
    intro: 'Một lab client/server bằng Python để tìm hiểu mã hóa bảo vệ được gì — và ứng dụng còn phải làm gì.',
    project: 'RAT-HAILAMDEV',
    status: 'Học tập & nghiên cứu phòng thủ',
    source: 'Khám phá mã nguồn',
    inspect: 'Khám phá kiến trúc',
    brief: 'Hiểu dự án trong 30 giây',
    summary: 'Tôi xây dựng một lab quản trị từ xa nhỏ để tìm hiểu socket, TLS và cách xử lý thông điệp. Bài học đáng nhớ: kết nối đã mã hóa vẫn cần xác thực, phân quyền và giới hạn rõ ràng.',
    facts: [
      { label: 'Trọng tâm', value: 'Python & lập trình mạng' },
      { label: 'Kết nối', value: 'TLS 1.3 / TCP socket' },
      { label: 'Giao thức', value: 'JSON phân tách bằng dòng mới' },
      { label: 'Phạm vi', value: 'Lab học tập biệt lập' },
    ],
    architecture: 'Theo dấu một kết nối.',
    architectureIntro: 'Chọn từng lớp để xem quyết định kỹ thuật phía sau.',
    modelLabel: 'Khám phá kiến trúc',
    diagramLabel: 'Sơ đồ minh họa · không kết nối thật',
    layers: [
      { id: 'client', title: 'Client', tag: '01 / GIAO DIỆN', short: 'CLI · gửi / nhận', heading: 'Giao diện nhỏ, thông điệp rõ.', body: 'Client dòng lệnh trao đổi yêu cầu và phản hồi theo từng action với server. Mỗi thông điệp JSON kết thúc bằng ký tự xuống dòng, giúp bên nhận tách các thông điệp trong luồng byte.', noteLabel: 'Liên hệ với full-stack', note: 'API cũng cần trả lời câu hỏi này: bên nhận nhận biết điểm kết thúc của một thông điệp như thế nào?', evidence: 'Giao thức JSON', anchor: '#features' },
      { id: 'transport', title: 'TLS 1.3', tag: '02 / KẾT NỐI', short: 'Kênh truyền mã hóa', heading: 'Bảo vệ dữ liệu trên đường truyền.', body: 'TLS bọc bên ngoài TCP socket. Xác minh chứng chỉ là một phần của việc tin cậy đầu bên kia; chứng chỉ tự ký trong dự án phù hợp với môi trường học tập.', noteLabel: 'Điểm cần phân biệt', note: 'Mã hóa bảo vệ kết nối. Nó không quyết định client được phép thực hiện hành động nào trong ứng dụng.', evidence: 'Kết nối & môi trường lab', anchor: '#security-notes' },
      { id: 'server', title: 'Server', tag: '03 / ỨNG DỤNG', short: 'Xử lý · trạng thái phiên', heading: 'Nơi ứng dụng phải kiểm soát quyền.', body: 'Server Python điều phối yêu cầu, dùng lock khi quản lý client và lưu thông tin phiên khi dừng. Đây là bài tập thực tế về xử lý đồng thời và trạng thái dùng chung.', noteLabel: 'Giới hạn hiện tại', note: 'Repo ghi rõ chưa có xác thực và phân quyền client. Đây là lab nghiên cứu, chưa phải sản phẩm bảo mật dùng trong production.', evidence: 'Giới hạn được ghi nhận', anchor: '#security-notes' },
    ],
    sourceNote: 'Đọc ghi chú trong repo',
    lessonsTitle: 'Tôi sẽ gia cố gì tiếp theo?',
    lessonsIntro: 'Nhìn lại lab hiện tại và xác định các lớp bảo vệ cần bổ sung. Đây là hướng cải thiện, chưa phải tính năng đã hoàn thành.',
    current: 'Trong lab hiện tại',
    next: 'Hướng cải thiện',
    lessons: [
      { title: 'Xác thực & phân quyền', current: 'Chưa triển khai xác thực và phân quyền client.', next: 'Xác thực client, sau đó kiểm tra quyền cho từng hành động với đặc quyền tối thiểu.' },
      { title: 'Giới hạn truy cập tệp', current: 'Đường dẫn tệp chưa được giới hạn trong sandbox.', next: 'Chỉ cho phép truy cập một thư mục làm việc cụ thể và kiểm tra đường dẫn tại điểm tiếp nhận.' },
      { title: 'Chức năng nhạy cảm', current: 'Các mô-đun tùy chọn ghi phím và chụp màn hình làm tăng tác động nếu bị lạm dụng.', next: 'Loại bỏ các chức năng này khỏi demo phòng thủ tối giản và giữ thử nghiệm trong môi trường biệt lập.' },
    ],
    takeawayLabel: 'Điều tôi mang vào công việc full-stack',
    takeaway: 'Nghĩ cả lúc hệ thống gặp vấn đề.',
    takeawayBody: 'Thiết kế giao thức, trạng thái đồng thời và ranh giới tin cậy đều liên quan đến backend web. Lab này giúp tôi giải thích cụ thể các quyết định đó cùng giới hạn của chúng.',
    footerNote: 'Nội dung dựa trên repository công khai. Sơ đồ chỉ minh họa kiến trúc, không chạy công cụ quản trị từ xa.',
  },
};
