const github = 'https://github.com/xuanhai0913/';

// Explanatory models, not results from running the linked research tools.
export const securityTopics = [
  {
    id: 'sqli', code: 'SQLi', repo: 'SQLI-HAILAMDEV', stack: 'Python / SQL / Flask', fresh: true,
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html', sourceName: 'OWASP · SQL injection prevention',
    en: {
      name: 'SQL injection', area: 'Database boundary',
      summary: 'When user input becomes part of a database command, it can change what the query does.',
      nodes: ['User input', 'Query builder', 'Database'], control: 'Parameterized query',
      steps: ['An application receives untrusted input.', 'String concatenation mixes input with SQL instructions.', 'The database may read or change data outside the intended request.'],
      defended: ['The same untrusted input reaches the application.', 'Parameters keep values separate from the query structure.', 'The database treats the input as a value, not as new instructions.'],
      impact: 'Data exposure or unauthorized changes.',
      defenses: ['Bind query parameters; avoid string-built SQL.', 'Allow-list dynamic identifiers and limit database privileges.', 'Test data-access boundaries and monitor unusual query failures.'],
      lesson: 'The boundary belongs in the data-access layer, not just the form validator.',
      evidence: 'Research prototype organized around SQL injection analysis, database adapters and a Flask coordination service.',
      limit: 'Repository scope is not evidence of detection accuracy or production readiness.',
    },
    vi: {
      name: 'SQL injection', area: 'Ranh giới cơ sở dữ liệu',
      summary: 'Khi dữ liệu người dùng bị ghép vào câu lệnh SQL, nó có thể làm truy vấn chạy khác với ý định ban đầu.',
      nodes: ['Dữ liệu đầu vào', 'Tạo truy vấn', 'Cơ sở dữ liệu'], control: 'Truy vấn tham số hóa',
      steps: ['Ứng dụng nhận dữ liệu chưa đáng tin cậy.', 'Ghép chuỗi khiến dữ liệu lẫn với câu lệnh SQL.', 'Truy vấn có thể đọc hoặc sửa dữ liệu ngoài phạm vi yêu cầu.'],
      defended: ['Ứng dụng vẫn nhận cùng dữ liệu đầu vào.', 'Tham số tách giá trị khỏi cấu trúc câu lệnh.', 'Cơ sở dữ liệu xử lý đầu vào như giá trị, không phải lệnh mới.'],
      impact: 'Lộ dữ liệu hoặc thay đổi dữ liệu trái phép.',
      defenses: ['Dùng tham số truy vấn, tránh ghép chuỗi SQL.', 'Allow-list tên bảng/cột động và cấp quyền DB tối thiểu.', 'Kiểm thử lớp truy cập dữ liệu, theo dõi lỗi truy vấn bất thường.'],
      lesson: 'Cần bảo vệ ngay tại lớp truy cập dữ liệu, không chỉ kiểm tra ở form.',
      evidence: 'Prototype nghiên cứu gồm các mô-đun phân tích SQL injection, adapter cơ sở dữ liệu và dịch vụ điều phối Flask.',
      limit: 'Phạm vi mô tả trong repo chưa chứng minh độ chính xác hay khả năng dùng trong production.',
    },
  },
  {
    id: 'xss', code: 'XSS', repo: 'klg-xss-hailamdev', stack: 'Python / JavaScript / Flask', fresh: true,
    source: 'https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html', sourceName: 'OWASP · XSS prevention',
    en: {
      name: 'Cross-site scripting', area: 'Browser boundary',
      summary: 'Untrusted content becomes executable code inside a page that the visitor trusts.',
      nodes: ['Untrusted content', 'Page rendering', 'Browser'], control: 'Safe rendering',
      steps: ['External content enters a page.', 'An unsafe rendering sink interprets the content as markup or script.', 'Code can act inside the visitor’s browser session.'],
      defended: ['External content enters the same page.', 'Context-aware encoding or vetted sanitization keeps content inert.', 'The browser displays the intended content without running injected code.'],
      impact: 'Page manipulation or actions in a user’s session.',
      defenses: ['Prefer safe text rendering and context-specific output encoding.', 'Sanitize intentional rich HTML with a maintained library.', 'Add a strict CSP as defense in depth; it does not replace safe rendering.'],
      lesson: 'Rich-text editors, previews and embeds all need a clear trust boundary.',
      evidence: 'Lab repository exploring XSS contexts and input-capture risks, with browser-analysis modules and a Flask service.',
      limit: 'The portfolio demonstrates the defensive concepts only. No capture or browser hooks run here.',
    },
    vi: {
      name: 'Cross-site scripting', area: 'Ranh giới trình duyệt',
      summary: 'Nội dung không đáng tin bị biến thành mã chạy trong trang mà người truy cập đang tin tưởng.',
      nodes: ['Nội dung bên ngoài', 'Render trang', 'Trình duyệt'], control: 'Render an toàn',
      steps: ['Nội dung bên ngoài được đưa vào trang.', 'Điểm render không an toàn diễn giải nội dung thành HTML hoặc script.', 'Mã có thể hoạt động trong phiên trình duyệt của người dùng.'],
      defended: ['Trang vẫn tiếp nhận nội dung bên ngoài.', 'Encode đúng ngữ cảnh hoặc sanitize giúp nội dung không trở thành mã thực thi.', 'Trình duyệt hiển thị nội dung mà không chạy mã được chèn vào.'],
      impact: 'Thay đổi giao diện hoặc thực hiện hành động trong phiên người dùng.',
      defenses: ['Ưu tiên render văn bản và encode đầu ra đúng ngữ cảnh.', 'Nếu cần HTML phong phú, sanitize bằng thư viện được duy trì.', 'Dùng CSP chặt chẽ như lớp bổ sung, không thay thế render an toàn.'],
      lesson: 'Editor, preview và nội dung nhúng đều cần ranh giới tin cậy rõ ràng.',
      evidence: 'Repo lab tìm hiểu các ngữ cảnh XSS và rủi ro thu thập đầu vào, với mô-đun phân tích trình duyệt và dịch vụ Flask.',
      limit: 'Portfolio chỉ minh họa kiến thức phòng thủ, không chạy chức năng thu thập hay hook trình duyệt.',
    },
  },
  {
    id: 'ddos', code: 'DDoS', repo: 'DDOS-HAILAMDEV', stack: 'Python / asyncio / Traffic analysis',
    source: 'https://developers.cloudflare.com/learning-paths/prevent-ddos-attacks/concepts/ddos-prevention/', sourceName: 'Cloudflare · DDoS prevention',
    en: {
      name: 'Denial of service', area: 'Availability boundary',
      summary: 'Too much hostile traffic consumes the capacity that real users need. Distributed attacks come from many sources.',
      nodes: ['Traffic sources', 'Network edge', 'Application'], control: 'Layered traffic controls',
      steps: ['Many sources create a traffic surge.', 'Unfiltered traffic reaches limited application resources.', 'Legitimate users face slow responses or an unavailable service.'],
      defended: ['The traffic surge reaches the network edge.', 'Upstream filtering, rate limits and caching reduce origin load.', 'More capacity remains for legitimate requests; controls still need tuning.'],
      impact: 'Slow or unavailable services.',
      defenses: ['Use upstream DDoS mitigation for volumetric attacks.', 'Apply route-specific rate limits, caching and resource budgets.', 'Monitor saturation and rehearse an incident response plan.'],
      lesson: 'Availability is an architecture decision, not simply a bigger server.',
      evidence: 'Traffic monitoring and synthetic DoS/DDoS simulation modules for exploring thresholds and mitigation policies.',
      limit: 'Generated simulation metrics are not real network benchmarks.',
    },
    vi: {
      name: 'Từ chối dịch vụ', area: 'Khả năng phục vụ',
      summary: 'Lưu lượng gây hại chiếm tài nguyên mà người dùng thật cần. DDoS là tấn công từ nhiều nguồn cùng lúc.',
      nodes: ['Nguồn lưu lượng', 'Lớp biên mạng', 'Ứng dụng'], control: 'Kiểm soát nhiều lớp',
      steps: ['Nhiều nguồn tạo lượng truy cập tăng đột biến.', 'Lưu lượng chưa lọc dồn vào tài nguyên hữu hạn của ứng dụng.', 'Người dùng thật gặp phản hồi chậm hoặc không truy cập được.'],
      defended: ['Lưu lượng tăng đột biến tới lớp biên mạng.', 'Lọc upstream, rate limit và cache giảm tải cho máy chủ gốc.', 'Ứng dụng giữ thêm tài nguyên cho yêu cầu hợp lệ; vẫn cần tinh chỉnh.'],
      impact: 'Dịch vụ chậm hoặc ngừng phục vụ.',
      defenses: ['Dùng dịch vụ chống DDoS upstream cho tấn công lưu lượng lớn.', 'Đặt rate limit theo route, cache và giới hạn tài nguyên.', 'Theo dõi mức quá tải và chuẩn bị quy trình xử lý sự cố.'],
      lesson: 'Khả năng chịu tải đến từ kiến trúc, không chỉ từ máy chủ mạnh hơn.',
      evidence: 'Các mô-đun theo dõi lưu lượng và mô phỏng DoS/DDoS bằng dữ liệu tổng hợp để tìm hiểu ngưỡng và chính sách giảm tải.',
      limit: 'Số liệu mô phỏng được sinh ra, không phải benchmark mạng thực tế.',
    },
  },
  {
    id: 'malware', code: 'MAL', repo: 'Malware-HAILAMDEV', stack: 'Python / LIEF / Capstone',
    source: 'https://github.com/xuanhai0913/Malware-HAILAMDEV', sourceName: 'Malware-HAILAMDEV · README',
    en: {
      name: 'Malware analysis', area: 'Execution boundary',
      summary: 'Malware abuses code execution. Analysis gathers clues about a file before deciding how to handle it.',
      nodes: ['Unknown file', 'Inspection', 'Host system'], control: 'Isolation & review',
      steps: ['An unknown file arrives.', 'Its origin and behavior are not reviewed.', 'Executing it can expose the host and its data.'],
      defended: ['The unknown file is kept away from the working host.', 'Static inspection gathers metadata, strings and structural clues.', 'Findings guide quarantine or further isolated analysis, not a guarantee of safety.'],
      impact: 'Host compromise and loss of data integrity.',
      defenses: ['Inspect unknown files without executing them on a working machine.', 'Use isolated environments and least privilege for deeper analysis.', 'Combine evidence; entropy or one signature alone is not a verdict.'],
      lesson: 'Distinguish a useful signal from a reliable security conclusion.',
      evidence: 'Static-analysis code for file metadata, strings, entropy and disassembly using LIEF and Capstone.',
      limit: 'A research prototype, not a validated malware detector or production defense platform.',
    },
    vi: {
      name: 'Phân tích mã độc', area: 'Ranh giới thực thi',
      summary: 'Mã độc lợi dụng việc thực thi chương trình. Phân tích tệp giúp thu thập dấu hiệu trước khi quyết định cách xử lý.',
      nodes: ['Tệp chưa rõ nguồn', 'Kiểm tra tệp', 'Máy làm việc'], control: 'Cách ly & phân tích',
      steps: ['Một tệp chưa rõ nguồn được tiếp nhận.', 'Nguồn gốc và hành vi của tệp chưa được kiểm tra.', 'Chạy tệp có thể gây nguy hiểm cho máy và dữ liệu.'],
      defended: ['Tệp được giữ tách biệt với máy làm việc.', 'Phân tích tĩnh thu thập metadata, chuỗi và cấu trúc tệp.', 'Dấu hiệu giúp chọn cách ly hoặc phân tích tiếp, chưa bảo đảm tệp an toàn.'],
      impact: 'Máy bị xâm nhập, dữ liệu bị ảnh hưởng.',
      defenses: ['Kiểm tra tệp lạ mà không chạy trên máy làm việc.', 'Dùng môi trường biệt lập và quyền tối thiểu khi phân tích sâu.', 'Kết hợp nhiều dấu hiệu; entropy hay một chữ ký chưa đủ kết luận.'],
      lesson: 'Phân biệt dấu hiệu hữu ích với kết luận bảo mật đáng tin.',
      evidence: 'Mã phân tích tĩnh metadata, chuỗi, entropy và disassembly bằng LIEF và Capstone.',
      limit: 'Prototype nghiên cứu, chưa phải công cụ phát hiện mã độc đã được kiểm chứng.',
    },
  },
  {
    id: 'rat', code: 'RAT', repo: 'RAT-HAILAMDEV', stack: 'Python / TLS 1.3 / TCP',
    source: 'https://github.com/xuanhai0913/RAT-HAILAMDEV#security-notes', sourceName: 'RAT-HAILAMDEV · Security notes',
    en: {
      name: 'Remote access & trust', area: 'Identity boundary',
      summary: 'Remote administration becomes a security risk when a connection is trusted without checking who can do what.',
      nodes: ['Remote client', 'Access boundary', 'Server action'], control: 'Identity & permissions',
      steps: ['A remote client connects through an encrypted channel.', 'Encryption alone does not authorize the requested action.', 'An unchecked action can affect server files or state.'],
      defended: ['The client establishes a verified encrypted connection.', 'Client identity and action-level permissions are checked.', 'Only scoped actions are allowed and recorded for review.'],
      impact: 'Unintended remote control or file access.',
      defenses: ['Verify peer identity in addition to encrypting transport.', 'Authorize each action and constrain filesystem access.', 'Keep auditable records and remove unnecessary capabilities.'],
      lesson: 'An encrypted connection is not the same as an authorized request.',
      evidence: 'Python client/server lab with TLS 1.3, newline-delimited JSON and lock-protected session handling.',
      limit: 'Authentication, authorization and filesystem sandboxing remain proposed improvements.',
    },
    vi: {
      name: 'Truy cập từ xa & quyền', area: 'Ranh giới danh tính',
      summary: 'Quản trị từ xa trở thành rủi ro khi hệ thống tin kết nối mà chưa kiểm tra ai được phép làm gì.',
      nodes: ['Client từ xa', 'Kiểm soát truy cập', 'Hành động server'], control: 'Xác thực & phân quyền',
      steps: ['Client từ xa kết nối qua kênh mã hóa.', 'Mã hóa không tự cấp quyền cho hành động được yêu cầu.', 'Hành động không được kiểm tra có thể ảnh hưởng tệp hoặc trạng thái server.'],
      defended: ['Client thiết lập kết nối mã hóa được xác minh.', 'Hệ thống kiểm tra danh tính và quyền cho từng hành động.', 'Chỉ hành động đúng phạm vi được thực hiện và ghi nhận.'],
      impact: 'Điều khiển từ xa hoặc truy cập tệp ngoài ý muốn.',
      defenses: ['Xác minh danh tính bên kết nối, bên cạnh mã hóa đường truyền.', 'Phân quyền từng hành động và giới hạn truy cập hệ thống tệp.', 'Ghi log có thể kiểm tra và bỏ chức năng không cần thiết.'],
      lesson: 'Kết nối được mã hóa chưa có nghĩa là yêu cầu đã được cấp quyền.',
      evidence: 'Lab client/server Python với TLS 1.3, JSON phân tách bằng dòng mới và lock khi quản lý phiên.',
      limit: 'Xác thực, phân quyền và sandbox tệp vẫn là các hướng cải thiện đề xuất.',
    },
  },
];

export const repositoryUrl = topic => `${github}${topic.repo}`;

export const hubCopy = {
  en: {
    eyebrow: 'Security research / HAILAMDEV', title: 'Understand the attack.', accent: 'Design the defense.',
    intro: 'A full-stack developer’s field notes on the boundaries that protect data, browsers and services.',
    explore: 'Explore the threat map', projects: 'Research repositories', back: 'Portfolio',
    labCount: 'research projects', newCount: 'new web-security labs', mode: 'Interactive field notes',
    mapTitle: 'Where does trust break?', mapIntro: 'Choose a topic. Follow the flow, then compare it with the defensive design.',
    topics: 'Security topics', risk: 'Without the control', protected: 'With the control', switch: 'Show defensive design',
    model: 'Conceptual walkthrough · no live attack', play: 'Play walkthrough', pause: 'Pause', replay: 'Replay', next: 'Next step',
    stage: 'Step', impact: 'What is at risk', defense: 'How to reduce the risk', takeaway: 'What I take into full-stack work',
    learn: 'Read the reference', related: 'Related research', source: 'View repository', study: 'Architecture case study',
    shelfTitle: 'From concepts to code.', shelfIntro: 'Five independent research projects. Scope and limitations are listed beside the work.',
    fresh: 'NEW', prototype: 'RESEARCH PROTOTYPE', note: 'The controls shown above explain defensive designs. They are not a claim that every linked prototype implements them.',
    footer: 'My focus: understand failure modes, review the evidence, and turn that understanding into safer application design.',
  },
  vi: {
    eyebrow: 'Nghiên cứu bảo mật / HAILAMDEV', title: 'Hiểu cách tấn công.', accent: 'Thiết kế cách phòng vệ.',
    intro: 'Ghi chép của một lập trình viên full-stack về những ranh giới bảo vệ dữ liệu, trình duyệt và dịch vụ.',
    explore: 'Khám phá bản đồ rủi ro', projects: 'Các repo nghiên cứu', back: 'Portfolio',
    labCount: 'dự án nghiên cứu', newCount: 'lab bảo mật web mới', mode: 'Ghi chép tương tác',
    mapTitle: 'Rủi ro bắt đầu từ đâu?', mapIntro: 'Chọn một chủ đề, theo dõi luồng xử lý rồi so sánh với thiết kế có phòng vệ.',
    topics: 'Chủ đề bảo mật', risk: 'Chưa có lớp bảo vệ', protected: 'Có lớp bảo vệ', switch: 'Xem thiết kế phòng vệ',
    model: 'Minh họa nguyên lý · không chạy tấn công', play: 'Chạy minh họa', pause: 'Tạm dừng', replay: 'Xem lại', next: 'Bước tiếp',
    stage: 'Bước', impact: 'Điều gì bị ảnh hưởng', defense: 'Giảm rủi ro như thế nào', takeaway: 'Bài học đưa vào công việc full-stack',
    learn: 'Đọc tài liệu tham khảo', related: 'Nghiên cứu liên quan', source: 'Xem repository', study: 'Case study kiến trúc',
    shelfTitle: 'Từ nguyên lý đến mã nguồn.', shelfIntro: 'Năm dự án nghiên cứu độc lập, kèm phạm vi thực hiện và giới hạn hiện tại.',
    fresh: 'MỚI', prototype: 'PROTOTYPE NGHIÊN CỨU', note: 'Các lớp bảo vệ phía trên minh họa thiết kế phòng thủ, không có nghĩa mọi prototype đã triển khai đầy đủ.',
    footer: 'Điều tôi theo đuổi: hiểu cách hệ thống có thể gặp vấn đề, kiểm tra bằng chứng và áp dụng vào thiết kế ứng dụng an toàn hơn.',
  },
};
