const PORTFOLIO_DATA = {
  profile: {
    name: 'Nguyen Xuan Hai',
    title: 'Full-Stack Developer',
    location: 'Ho Chi Minh City, Vietnam',
    summary: 'Full-stack developer working across React, ASP.NET Core, NestJS, Python/Odoo and AI-assisted engineering workflows.',
    languages: ['Vietnamese (native)', 'English (B1.4; technical reading and written communication)'],
    coreSkills: [
      'React',
      'Node.js',
      'ASP.NET Core',
      'NestJS',
      'Python',
      'Odoo 18',
      'PostgreSQL',
      'SQL Server',
      'TypeScript',
      'AI agent workflows',
    ],
  },
  stats: {
    productionProjects: 7,
    portfolioProjects: 13,
    companies: 3,
    certifications: 45,
    awsCredentials: 28,
  },
  projects: [
    {
      id: 'ddos-lab',
      name: 'DDOS-HAILAMDEV · Defense Toolkit',
      category: 'Independent security research · bảo mật mạng',
      stack: ['Python', 'asyncio', 'Traffic Analysis'],
      evidence: 'Monitoring and synthetic DoS/DDoS simulation modules. Simulation metrics use generated data, not real network benchmarks; research prototype.',
      role: 'Creator · Network Security Research',
      url: 'https://github.com/xuanhai0913/DDOS-HAILAMDEV',
    },
    {
      id: 'malware-lab',
      name: 'Malware-HAILAMDEV · Analysis Framework',
      category: 'Independent security research · phân tích mã độc',
      stack: ['Python', 'LIEF', 'Capstone', 'Static Analysis'],
      evidence: 'Static-analysis code for file metadata, strings, entropy and disassembly. Broader malware analysis framework is a research prototype, not a validated production defense platform.',
      role: 'Creator · Malware Analysis Research',
      url: 'https://github.com/xuanhai0913/Malware-HAILAMDEV',
    },
    {
      id: 'security-lab',
      name: 'RAT-HAILAMDEV · Security Lab',
      category: 'Independent security research lab · bảo mật · lập trình mạng',
      stack: ['Python', 'TLS 1.3', 'TCP sockets', 'JSON', 'Threading'],
      evidence: 'Educational client/server prototype with TLS 1.3, newline-delimited JSON and lock-protected session handling. Client authentication, authorization and filesystem sandboxing are not implemented; not a production security product.',
      role: 'Creator · Python and networking',
      url: 'https://my-portfolio-nxh.vercel.app/projects/security-lab',
      repository: 'https://github.com/xuanhai0913/RAT-HAILAMDEV',
    },
    {
      id: 'oakmind',
      name: 'OakMind Group Corporate Platform',
      category: 'Production client platform',
      stack: ['React 19', 'ASP.NET Core 8', 'SQL Server', 'Cloudflare R2'],
      evidence: 'Shipped a live bilingual corporate CMS/admin with SEO, analytics, video and R2 media workflows in 28 authored commits.',
      role: 'Full-stack development and business analysis',
      url: 'https://oakmindgroup.com/',
    },
    {
      id: 'greatlink',
      name: 'Great Link Mai House',
      category: 'Production client platform',
      stack: ['React 18', 'ASP.NET Core', 'SignalR'],
      evidence: 'Rebuilt legacy WordPress and ASP.NET MVC publishing workflows as a maintainable React and ASP.NET Core platform.',
      role: 'Full-stack delivery',
      url: 'https://greatlinkmaihouse.com/',
    },
    {
      id: 'vnmediahub',
      name: 'VN Media Hub',
      category: 'Production client platform',
      stack: ['React 18', 'ASP.NET Core 8', 'Redis'],
      evidence: 'Delivered CMS workflows with authentication, moderation, caching, structured logging, SEO, reporting and PDF exports.',
      role: 'Full-stack delivery',
      url: 'https://vnmediahub.com',
    },
    {
      id: 'chongscam',
      name: 'ChongScam Trust Platform',
      category: 'Production client platform',
      stack: ['React 19', 'NestJS 11', 'PostgreSQL', 'Jest'],
      evidence: 'Delivered a client-operated platform spanning 22 controllers, 20 SQL migrations and 12 Jest/e2e test suites.',
      role: 'Full-stack developer',
      url: 'https://chongscam.vn/',
    },
    {
      id: 'routelab',
      name: 'RouteLab Shortest Path Lab',
      category: 'Independent engineering project',
      stack: ['React', 'TypeScript', 'Express', 'Vitest'],
      evidence: 'Implemented four shortest-path solvers, replay visualization, automated tests and backend algorithm CI.',
      role: 'Creator and developer',
      url: 'https://tsp-delivery-route-optimizer.vercel.app/',
    },
    {
      id: 'agritrace',
      name: 'AgriTrace Blockchain Traceability',
      category: 'Independent engineering project',
      stack: ['React', 'Express', 'PostgreSQL', 'Solidity', 'IPFS'],
      evidence: 'Built multi-role supply-chain workflows with hybrid on-chain/off-chain evidence and QR verification.',
      role: 'Creator and developer',
      url: 'https://github.com/xuanhai0913/agri-traceability-system',
    },
  ],
  experience: [
    {
      id: 'betodemy',
      company: 'Betodemy',
      role: 'Full-Stack Developer',
      period: 'Feb 2026 – Present',
      summary: 'Builds and maintains student portals, online classes, admin tools, gamified practice and multilingual learning content in a five-developer product team.',
      evidence: 'Delivered 70+ merged MRs and closed 70+ authored issues across document-editor, online-class and student/admin workflows.',
      stack: ['React 19', 'NestJS', 'PostgreSQL', 'Redis', 'BullMQ', 'Nx', 'GitLab CI/CD'],
      url: 'https://betodemy.com/',
    },
    {
      id: 'aipower',
      company: 'AI Power',
      role: 'Full-Stack Developer · Odoo/Python',
      period: 'May 2026 – Sep 2026',
      summary: 'Developed and supported an Odoo 18 ERP for automotive dealerships across sales, after-sales service, spare parts, warranty and accounting workflows.',
      evidence: 'Supported debugging and fixes across all 18 custom modules and 99+ Python files while preserving the 18-state service workflow.',
      stack: ['Python 3.12', 'Odoo 18', 'PostgreSQL', 'QWeb/XML', 'Docker', 'GitLab CI'],
      url: 'https://aipower.vn/vi',
    },
    {
      id: 'oakmind-experience',
      company: 'OakMind Group',
      role: 'Full-Stack Developer · Business Analysis',
      period: 'Oct 2024 – Jan 2026',
      summary: 'Handled requirement clarification, full-stack development and releases across three live web products.',
      evidence: 'Took all three products from requirement clarification through release; delivered the live corporate website in 28 authored commits.',
      stack: ['React 18/19', 'ASP.NET Core 8', 'SQL Server', 'Redis', 'SignalR', 'Cloudflare R2'],
      url: 'https://oakmindgroup.com/',
    },
  ],
  credentials: [
    {
      id: 'aws-agentic-ai',
      name: 'AWS Agentic AI Demonstrated',
      issuer: 'AWS Training & Certification',
      date: 'Aug 2026',
      topics: ['AWS', 'Agentic AI', 'Amazon Bedrock', 'Guardrails'],
      proof: 'Timed hands-on lab microcredential',
      url: 'https://www.credly.com/badges/f6bcde81-b1ba-4570-a327-e632bae4a3e5/public_url',
    },
    {
      id: 'aws-cloud-essentials',
      name: 'AWS Knowledge: Cloud Essentials',
      issuer: 'AWS Training & Certification',
      date: 'Jul 2026',
      topics: ['AWS', 'Cloud fundamentals'],
      proof: 'Verified training badge',
      url: 'https://www.credly.com/badges/1146b467-7e68-4c92-9f36-83ad6858df10/public_url',
    },
    {
      id: 'aws-events-workflows',
      name: 'AWS Knowledge: Events and Workflows',
      issuer: 'AWS Training & Certification',
      date: 'Jul 2026',
      topics: ['Step Functions', 'EventBridge', 'SQS', 'SNS'],
      proof: 'Verified training badge',
      url: 'https://www.credly.com/badges/7ec9cba5-c356-4f45-8692-95809e2f3e2a/public_url',
    },
    {
      id: 'aws-serverless',
      name: 'AWS Knowledge: Serverless',
      issuer: 'AWS Training & Certification',
      date: 'Jul 2026',
      topics: ['Lambda', 'API Gateway', 'Serverless'],
      proof: 'Verified training badge',
      url: 'https://www.credly.com/badges/6b334133-b6df-424e-a3ac-a46894d520ee/public_url',
    },
    {
      id: 'google-cloud-infrastructure',
      name: 'Essential Google Cloud Infrastructure: Foundation',
      issuer: 'Google Cloud Skills Boost',
      date: 'Jul 2026',
      topics: ['Google Cloud', 'Cloud infrastructure'],
      proof: 'Verified completion badge',
      url: 'https://www.skills.google/public_profiles/03bc8f46-a5c3-423f-8d12-f235d5da8486/badges/25783325',
    },
    {
      id: 'gemini-faculty',
      name: 'Gemini Certified Faculty',
      issuer: 'Google for Education',
      date: '2025',
      topics: ['Gemini', 'Generative AI', 'Education'],
      proof: 'Verified faculty credential',
      url: 'https://edu.google.accredible.com/b72948bf-9762-446f-b771-5eaadd88ccf9?key=8346ffe5eeaa608d615483a398c1a29a43f53ad92dcd7f8a4a5986d28124ead9',
    },
  ],
  contacts: [
    { id: 'email', label: 'Email', value: 'xuanhai0913750452@gmail.com', url: 'mailto:xuanhai0913750452@gmail.com' },
    { id: 'phone', label: 'Phone', value: '+84 929 501 116', url: 'tel:+84929501116' },
    { id: 'linkedin', label: 'LinkedIn', value: 'linkedin.com/in/xuanhai0913', url: 'https://www.linkedin.com/in/xuanhai0913/' },
    { id: 'github', label: 'GitHub', value: 'github.com/xuanhai0913', url: 'https://github.com/xuanhai0913' },
    { id: 'upwork', label: 'Upwork', value: 'upwork.com/freelancers/xuanhai0913', url: 'https://www.upwork.com/freelancers/xuanhai0913' },
    { id: 'cv', label: 'CV', value: 'English CV', url: 'https://my-portfolio-nxh.vercel.app/CV_NguyenXuanHai_visual.pdf' },
  ],
};

module.exports = { PORTFOLIO_DATA };
